name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/documentation.yml
      - Sources/Quantum/**.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources/Quantum"
          output: "Documentation"
       name: Fix permissions
        run: 'sudo chown --recursive $USER Documentation'
      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: wiki
          folder: Documentation
          single-commit: true
